FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY mvnw ./
RUN chmod +x mvnw

COPY .mvn .mvn
COPY pom.xml ./

RUN ./mvnw dependency:resolve

COPY src ./src

RUN ./mvnw package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/*.jar ./app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "./app.jar"]