server {
    listen 80;
    server_name _;

    client_max_body_size 100M;

    tcp_nodelay on;

    location / {
        proxy_pass http://bbhmm_frontend:5173;

        # Suporte a WebSockets (Necessário para o Vite / HMR)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Repassa o Host correto enviado pelo Cloudflare
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;

        proxy_pass http://bbhmm_backend:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /perfil/ {
        proxy_pass http://storage:9000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
    }
}