# ===============================
# SPRING
# ===============================
spring.application.name=BBHMM
logging.level.com.BBHMM.backend.BBHMM=${LOGGER_APPLICATION_LEVEL:INFO}

config.spring.security.token.secret=${JWT_TOKEN:defaultSecret}
config.spring.security.issuer=${JWT_ISSUER:defaultIssuer}
config.spring.cors.accepted.url=${CORS_ACCEPTED_URL}
# springdoc.api-docs.enabled=false
# springdoc.swagger-ui.enabled=false

spring.output.ansi.enabled=ALWAYS

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===============================
# DATASOURCE - MYSQL
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/provider}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD}

# ===============================
# MAIL SERVICE
# ===============================
spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_HOST_PORT:1025}
spring.mail.sender.email=${MAIL_SENDER:noreply@minhaapp.com}
spring.mail.sender.frontend.domain.url=${MAIL_FRONTEND_DOMAIN:localhost:5173}

spring.mail.properties.mail.smtp.auth=${MAIL_AUTH_FLAG:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_FLAG:false}

# # ===============================
# # FLYWAY
# # ===============================
# spring.flyway.enabled=${ENABLE_FLYWAY_MIGRATION:true}

# # ===============================
# # SECURITY
# # ===============================
# security.permit-all-patterns= "/health,/swagger-ui/**,/auth/login"
# security.secret.token= ${SECURITY_SECRET_TOKEN:token-secret}