spring.application.name=BBHMM
api.security.token.secret=${JWT_TOKEN:defaultSecret}
api.security.auth.issuer=${AUTH_ISSUER:defaultIssuer}

config.spring.cors.accepted.url=${CORS_ACCEPTED_URL:http//localhost}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/provider}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD}